import { StyleSheet, Dimensions } from 'react-native';
import { COLOR_TOKENS, SHADOW_TOKENS, OVERLAY_TOKENS, BLUR_INTENSITY, FONT_FAMILY } from '../../constants/designTokens';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const C = COLOR_TOKENS;
const O = OVERLAY_TOKENS;
const F = FONT_FAMILY;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.backgroundApp,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 58,
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  headerLogoMark: {
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerLogoImage: {
    width: 22,
    height: 22,
  },
  headerLogoFallbackIcon: {
    opacity: 0.95,
  },
  headerSubtitle: {
    fontSize: 12,
    fontFamily: F.medium,
    fontWeight: '500',
    letterSpacing: 0.3,
    marginTop: 2,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: F.bold,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  title: {
    fontSize: 23,
    fontFamily: 'Pretendard-Bold',
    color: C.textPrimary,
    letterSpacing: -0.3,
  },
  headerButton: {
    padding: 8,
    backgroundColor: C.backgroundElevated,
    borderRadius: 6,
    ...SHADOW_TOKENS.subtle,
  },
  headerButtonNeumorphLight: {
    borderRadius: 999,
    overflow: 'visible',
    shadowColor: '#FFFFFF',
    shadowOffset: { width: -2, height: -2 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 4,
  },
  headerButtonNeumorphDark: {
    borderRadius: 999,
    overflow: 'visible',
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  headerButtonPill: {
    borderRadius: 999,
    overflow: 'hidden',
  },
  headerButtonPillBlur: {
    width: 36,
    height: 36,
    borderRadius: 999,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    backgroundColor: O.blurSurfaceMedium,
    borderWidth: 1,
    borderColor: O.glassBorderHighlight,
  },
  content: {
    flex: 1,
  },

  sectorNeumorphLight: {
    shadowColor: '#FFFFFF',
    shadowOffset: { width: -3, height: -3 },
    shadowOpacity: 1.0,
    shadowRadius: 5,
  },

  // Group 1: Image + Settings
  imageGroupOuter: {
    marginHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 4,
  },
  imageGroupInner: {
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: 'rgb(222, 222, 224)',
  },

  // Group 2: Color Palette (shadow inherited from imageGroupOuter)
  paletteGroupOuter: {
    marginTop: 24,
  },
  paletteGroupInner: {
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: 'rgb(222, 222, 224)',
  },

  // Image Card
  imageCard: {
    height: 240,
    margin: 15,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  sourceImageBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: O.scrimDark,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
  },
  sourceImageText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontFamily: F.medium,
    fontWeight: '500',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: O.glassWhiteLoading,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: C.textPrimary,
    marginTop: 12,
  },
  reExtractIconButton: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: O.scrimDark,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loupe: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    backgroundColor: O.glassWhiteThin,
    justifyContent: 'center',
    alignItems: 'center',
    ...SHADOW_TOKENS.medium,
  },
  loupeCrosshair: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#fff',
  },
  valueOverlayButton: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 18,
  },
  valueOverlayButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: F.bold,
    fontWeight: '700',
    letterSpacing: 0.35,
  },
  imageCardEmptyBorder: {
    backgroundColor: 'transparent',
    borderRadius: 16,
    padding: 15,
  },
  imageCardEmpty: {
    height: 280,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 28,
    paddingHorizontal: 32,
    backgroundColor: 'rgba(240,240,242,1)',
    borderRadius: 16,
    overflow: 'hidden',
  },
  imageSourceButtons: {
    flexDirection: 'row',
    gap: 16,
    width: '100%',
    height: 66,
  },
  imageSourceCardGlow: {
    flex: 1,
    shadowOffset: { width: 3, height: 4 },
    shadowOpacity: 0.9,
    shadowRadius: 14,
    elevation: 6,
  },
  imageSourceCard: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    gap: 8,
    overflow: 'hidden',
  },
  imageSourceCardText: {
    fontSize: 14,
    fontFamily: F.semiBold,
    fontWeight: '600',
    color: 'rgb(130, 130, 140)',
  },

  // Style Filters - Icon Grid
  styleFiltersContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
    gap: 6,
  },
  styleFilterButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 6,
    backgroundColor: C.backgroundElevated,
    gap: 4,
    ...SHADOW_TOKENS.none,
  },
  styleFilterText: {
    fontSize: 12,
    color: C.textSecondary,
    fontFamily: F.bold,
    fontWeight: '700',
    letterSpacing: 0.2,
  },

  // CVD Simulation Row
  cvdRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginHorizontal: 16,
    marginBottom: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    gap: 4,
  },
  cvdLabel: {
    fontSize: 11,
    fontFamily: F.semiBold,
    fontWeight: '600' as const,
    marginRight: 6,
  },
  cvdToggleGroup: {
    flex: 1,
    flexDirection: 'row' as const,
    gap: 3,
    backgroundColor: C.backgroundSurfaceAlt,
    borderRadius: 5,
    padding: 3,
  },
  cvdOption: {
    flex: 1,
    paddingVertical: 6,
    borderRadius: 4,
    alignItems: 'center' as const,
  },
  cvdOptionText: {
    fontSize: 12,
    fontFamily: F.semiBold,
    fontWeight: '600' as const,
  },

  // Color Cards
  colorCardsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
    overflow: 'hidden',
  },
  paletteStepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingBottom: 10,
  },
  paletteStepperBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    justifyContent: 'center',
    alignItems: 'center',
  },
  paletteStepperCount: {
    fontSize: 13,
    fontFamily: F.semiBold,
    fontWeight: '600',
    minWidth: 16,
    textAlign: 'center',
    lineHeight: 26,
  },
  colorCard: {
    flex: 1,
    alignItems: 'center',
    minHeight: 48,
    paddingVertical: 4,
    paddingHorizontal: 1,
  },
  colorCardSelected: {},
  colorSwatchOuterLight: {
    width: '100%',
    borderRadius: 6,
    backgroundColor: COLOR_TOKENS.backgroundSurface,
  },
  colorSwatchOuter: {
    width: '100%',
    borderRadius: 6,
    backgroundColor: COLOR_TOKENS.backgroundSurface,
  },
  colorSwatchOuterSelected: {
  },
  colorSwatchMid: {
    width: '100%',
    borderRadius: 6,
  },
  colorSwatchMidSelected: {
  },
  colorSwatch: {
    width: '100%',
    height: 52,
    borderRadius: 6,
    borderTopWidth: 1.5,
    borderTopColor: O.neumorphInsetBorderTop,
  },
  colorSwatchSelected: {
  },
  colorSwatchInner: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 6,
    overflow: 'hidden',
  },
  swatchInsetShadowTop: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    height: '40%',
    backgroundColor: 'rgba(0,0,0,0.18)',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
  },
  swatchInsetHighlightBottom: {
    position: 'absolute' as const,
    bottom: 0,
    left: 0,
    right: 0,
    height: '35%',
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
  },
  cvdSplitOriginal: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '50%',
  },
  chipTriangle: {
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderBottomWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    marginTop: 4,
  },
  chipRank: {
    fontSize: 10,
    fontFamily: F.semiBold,
    fontWeight: '600',
    marginTop: 2,
  },
  colorCardsEmpty: {
    opacity: 0.6,
  },
  colorSwatchEmpty: {
    backgroundColor: 'rgba(0, 0, 0, 0.04)',
    borderWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Settings Row (2-row layout)
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 7,
    gap: 10,
  },
  settingsColumn: {
    flex: 1,
    gap: 4,
  },
  algorithmToggle: {
    flexDirection: 'row' as const,
    gap: 2,
    backgroundColor: C.backgroundSurfaceAlt,
    borderRadius: 6,
    padding: 3,
  },
  algorithmOption: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 5,
  },
  algorithmOptionText: {
    fontSize: 13,
    fontFamily: F.semiBold,
    fontWeight: '600' as const,
  },
  algorithmDesc: {
    fontSize: 11,
    fontFamily: F.medium,
    fontWeight: '500' as const,
    marginLeft: 6,
  },
  valueCheckButton: {
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 5,
    gap: 1,
  },
  valueCheckText: {
    fontSize: 13,
    fontFamily: F.semiBold,
    fontWeight: '600' as const,
  },
  valueCheckSubtext: {
    fontSize: 10,
    fontFamily: F.medium,
    fontWeight: '500' as const,
  },
  settingsColorColumn: {
    alignItems: 'center' as const,
    gap: 4,
  },
  settingsColorStepper: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
  },
  settingsDropdownLabel: {
    fontSize: 11,
    fontFamily: F.medium,
    fontWeight: '500' as const,
  },
  colorStepperBtn: {
    width: 26,
    height: 26,
    borderRadius: 4,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  colorCountBadge: {
    width: 28,
    height: 26,
    borderRadius: 4,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  colorCountBadgeText: {
    fontSize: 14,
    fontFamily: F.bold,
    fontWeight: '700' as const,
    color: '#FFFFFF',
  },

  // Inline Color Detail
  inlineColorDetailOuter: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 8,
    borderRadius: 10,
    overflow: 'hidden',
  },
  inlineColorDetail: {
    borderRadius: 10,
    padding: 12,
  },
  inlineColorDetailHeader: {
    flexDirection: 'row',
    gap: 12,
  },
  inlineColorSwatch: {
    width: 60,
    height: 60,
    borderRadius: 5,
  },
  inlineColorValues: {
    flex: 1,
    gap: 4,
  },
  inlineColorValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 4,
    gap: 8,
    minHeight: 44,
  },
  inlineColorLabel: {
    fontSize: 11,
    fontFamily: F.semiBold,
    fontWeight: '600',
    width: 28,
  },
  inlineColorValue: {
    flex: 1,
    fontSize: 13,
    fontFamily: 'monospace',
  },
  inlineColorPreview: {
    borderRadius: 6,
    padding: 14,
    marginBottom: 10,
  },
  previewTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inlineColorPreviewValue: {
    flex: 1,
    fontSize: 19,
    fontWeight: '700',
    fontFamily: 'monospace',
  },
  inlineColorCopyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: O.darkOnColorLight,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 4,
    gap: 6,
  },
  inlineColorCopyText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: F.semiBold,
    fontWeight: '600',
  },
  previewChannelContainer: {
    marginTop: 10,
    minHeight: 56,
    justifyContent: 'center',
  },
  previewChannelBars: {
    gap: 5,
  },
  previewChannelBarsPlaceholder: {
    height: 56,
  },
  previewChannelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  previewChannelLabel: {
    fontSize: 12,
    fontFamily: F.bold,
    fontWeight: '700',
    width: 14,
    textAlign: 'center',
    color: O.textOnColorPrimary,
    textShadowColor: O.textShadowDark,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  previewChannelTrack: {
    flex: 1,
    height: 8,
    backgroundColor: O.darkOnColorTrack,
    borderRadius: 2,
    overflow: 'hidden',
  },
  previewChannelFill: {
    height: '100%',
    borderRadius: 2,
  },
  previewChannelValue: {
    fontSize: 11,
    fontWeight: '600',
    fontFamily: 'monospace',
    width: 42,
    textAlign: 'right',
    color: O.textOnColorPrimary,
    textShadowColor: O.textShadowDark,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  formatSegment: {
    flexDirection: 'row',
    borderRadius: 5,
    padding: 3,
    marginBottom: 8,
  },
  formatSegmentButton: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 4,
    alignItems: 'center',
  },
  formatSegmentText: {
    fontSize: 13,
    fontFamily: F.bold,
    fontWeight: '700',
  },

  inlineVariationsSection: {
    marginTop: 0,
    borderRadius: 5,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 12,
  },

  // Slider - Inline
  sliderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  sliderLabel: {
    color: C.textSecondary,
    fontSize: 13,
    fontFamily: F.medium,
    fontWeight: '500',
    marginRight: 10,
  },
  sliderInline: {
    flex: 1,
    height: 32,
  },
  countBadge: {
    backgroundColor: C.accentPrimary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 3,
    marginLeft: 8,
  },
  countBadgeText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontFamily: F.semiBold,
    fontWeight: '600',
  },

  // Action Bar
  actionBar: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 16,
    paddingBottom: 40,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderTopWidth: 0.5,
    borderTopColor: 'rgba(255, 255, 255, 0.3)',
    gap: 12,
    overflow: 'hidden',
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderWidth: 0.5,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    gap: 6,
  },
  actionButtonText: {
    color: C.textSecondary,
    fontSize: 14,
    fontFamily: F.semiBold,
    fontWeight: '600',
  },
  saveButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: 'rgba(30, 30, 30, 0.7)',
    borderWidth: 0.5,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    gap: 6,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontFamily: F.bold,
    fontWeight: '700',
  },
  // exportButton: same as actionButton — use actionButton directly
  exportButton: {} as any,
  exportButtonText: {
    color: C.accentPrimary,
    fontSize: 14,
    fontFamily: F.semiBold,
    fontWeight: '600',
  },

  // Color Detail Modal
  colorDetailOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  colorDetailBackground: {
    flex: 1,
  },
  colorDetailContentOuter: {
    maxHeight: '70%',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: 'hidden',
  },
  colorDetailContent: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingBottom: 40,
    overflow: 'hidden',
  },
  colorDetailHandle: {
    width: 40,
    height: 4,
    backgroundColor: C.borderHandle,
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 16,
  },
  colorDetailHeader: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  colorDetailSwatch: {
    width: 80,
    height: 80,
    borderRadius: 8,
    ...SHADOW_TOKENS.subtle,
  },
  colorDetailValues: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'center',
    gap: 6,
  },
  colorValueCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.backgroundSurfaceAlt,
    borderRadius: 4,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  colorValueCompactLabel: {
    fontSize: 11,
    fontFamily: F.semiBold,
    fontWeight: '600',
    color: C.textSubtle,
    width: 28,
  },
  colorValueCompactText: {
    flex: 1,
    fontSize: 13,
    color: C.textPrimary,
    fontFamily: 'monospace',
  },
  // Modal Color Preview
  modalColorPreview: {
    height: 100,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  modalColorPreviewValue: {
    flex: 1,
    fontSize: 22,
    fontWeight: '700',
    fontFamily: 'monospace',
  },
  modalColorCopyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: O.darkOnColorLight,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 5,
    gap: 6,
  },
  modalColorCopyText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontFamily: F.semiBold,
    fontWeight: '600',
  },
  modalFormatSegment: {
    flexDirection: 'row',
    borderRadius: 8,
    padding: 3,
    marginBottom: 16,
  },
  modalFormatSegmentButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: 'center',
  },
  modalFormatSegmentText: {
    fontSize: 14,
    fontFamily: F.bold,
    fontWeight: '700',
  },

  // Value Variations
  variationsSection: {
    backgroundColor: O.glassSectionBg,
    borderRadius: 10,
    padding: 16,
    marginBottom: 16,
  },
  variationsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  variationsSectionTitle: {
    fontSize: 15,
    fontFamily: F.semiBold,
    fontWeight: '600',
    color: C.textPrimary,
  },
  hueShiftToggle: {
    flexDirection: 'row',
    backgroundColor: C.backgroundSurface,
    borderRadius: 4,
    padding: 2,
  },
  hueShiftOption: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 3,
  },
  hueShiftOptionText: {
    fontSize: 12,
    fontFamily: F.semiBold,
    fontWeight: '600',
    color: C.textSubtle,
  },
  variationStrip: {
    flexDirection: 'row',
    borderRadius: 6,
    overflow: 'hidden',
    marginBottom: 8,
  },
  variationCell: {
    flex: 1,
    alignItems: 'center',
  },
  variationCellBase: {
  },
  variationColor: {
    width: '100%',
    height: 40,
  },
  variationHex: {
    fontSize: 10,
    color: C.textSecondary,
    fontFamily: 'monospace',
    marginTop: 3,
  },
  variationLabel: {
    fontSize: 10,
    fontFamily: F.regular,
    color: C.textMuted,
  },
  variationsHint: {
    fontSize: 11,
    fontFamily: F.regular,
    color: C.textSubtle,
    textAlign: 'center',
    marginTop: 4,
  },

  // Color Harmony
  harmonySection: {
    backgroundColor: O.glassSectionBg,
    borderRadius: 10,
    padding: 16,
    marginBottom: 16,
  },
  harmonySectionTitle: {
    fontSize: 15,
    fontFamily: F.semiBold,
    fontWeight: '600',
    color: C.textPrimary,
    marginBottom: 12,
  },
  harmonyTypesScroll: {
    marginBottom: 8,
  },
  harmonyContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 12,
  },
  harmonyRightColumn: {
    flex: 1,
    gap: 6,
  },
  harmonyColorAngle: {
    fontSize: 10,
    fontFamily: 'monospace',
    marginTop: 1,
    width: 36,
    textAlign: 'center',
    paddingLeft: 2,
  },
  harmonyDesc: {
    fontSize: 12,
    fontFamily: F.regular,
    textAlign: 'center',
  },
  harmonyTypeButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: C.backgroundElevated,
    marginRight: 6,
    ...SHADOW_TOKENS.none,
  },
  harmonyTypeText: {
    fontSize: 12,
    fontFamily: F.semiBold,
    fontWeight: '600',
    color: C.textSubtle,
  },
  harmonyDescription: {
    fontSize: 12,
    fontFamily: F.regular,
    color: C.textSecondary,
    marginBottom: 12,
    textAlign: 'center',
  },
  harmonyColorsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
  },
  harmonyColorItem: {
    alignItems: 'center',
  },
  harmonyColorSwatch: {
    width: 36,
    height: 28,
    borderRadius: 6,
    marginBottom: 4,
    ...SHADOW_TOKENS.subtle,
  },
  harmonyColorSwatchBase: {
  },
  harmonyColorHex: {
    fontSize: 10,
    color: C.textSecondary,
    fontFamily: 'monospace',
    width: 36,
    textAlign: 'center',
  },

  // Save Modal
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: C.backgroundElevated,
    borderRadius: 8,
    padding: 24,
    width: '85%',
    maxWidth: 340,
    ...SHADOW_TOKENS.elevated,
  },
  modalTitle: {
    fontSize: 22,
    fontFamily: F.bold,
    fontWeight: 'bold',
    color: C.textPrimary,
    marginBottom: 16,
    textAlign: 'center',
  },
  modalInput: {
    backgroundColor: C.backgroundSurfaceAlt,
    borderRadius: 5,
    padding: 14,
    fontSize: 17,
    fontFamily: F.regular,
    color: C.textPrimary,
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 5,
    backgroundColor: C.backgroundSurfaceAlt,
    alignItems: 'center',
  },
  modalButtonPrimary: {
    backgroundColor: C.accentPrimary,
  },
  modalButtonText: {
    color: C.textSecondary,
    fontSize: 17,
    fontFamily: F.semiBold,
    fontWeight: '600',
  },
  modalButtonTextPrimary: {
    color: '#FFFFFF',
  },

  // Export Modal
  exportModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  exportModalBackground: {
    flex: 1,
  },
  exportModalContent: {
    backgroundColor: C.backgroundSurface,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    paddingHorizontal: 20,
    paddingBottom: 40,
    ...SHADOW_TOKENS.elevated,
  },
  exportModalHandle: {
    width: 40,
    height: 4,
    backgroundColor: C.borderHandle,
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 20,
  },
  exportModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  exportModalTitle: {
    fontSize: 22,
    fontFamily: F.bold,
    fontWeight: 'bold',
    color: C.textPrimary,
  },
  exportPreviewScroll: {
    maxHeight: 500,
  },

  // Palette Card for export
  paletteCard: {
    backgroundColor: C.backgroundElevated,
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    ...SHADOW_TOKENS.none,
  },
  paletteCardImage: {
    width: '100%',
    height: 160,
    borderRadius: 6,
    marginBottom: 12,
  },
  paletteCardSwatches: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 12,
  },
  paletteCardSwatch: {
    flex: 1,
    height: 40,
    borderRadius: 4,
  },
  paletteCardName: {
    fontSize: 19,
    fontFamily: F.bold,
    fontWeight: 'bold',
    color: C.textPrimary,
    marginBottom: 2,
  },
  paletteCardLabel: {
    fontSize: 12,
    fontFamily: F.regular,
    color: C.textMuted,
    letterSpacing: 1,
    marginBottom: 12,
  },
  paletteCardColors: {
    gap: 8,
  },
  paletteCardColorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  paletteCardColorDot: {
    width: 28,
    height: 28,
    borderRadius: 3,
  },
  paletteCardColorInfo: {
    flex: 1,
  },
  paletteCardHex: {
    fontSize: 14,
    fontWeight: '600',
    color: C.textPrimary,
    fontFamily: 'monospace',
  },
  paletteCardRgb: {
    fontSize: 12,
    color: C.textSecondary,
    fontFamily: 'monospace',
  },
  paletteCardWatermark: {
    textAlign: 'center',
    fontSize: 11,
    fontFamily: F.regular,
    color: C.textGhost,
    marginTop: 12,
  },
  paletteCardHistogram: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: C.borderSubtle,
  },
  paletteCardHistogramRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  paletteCardHistogramLabel: {
    fontSize: 12,
    fontFamily: F.regular,
    color: C.textMuted,
  },
  paletteCardHistogramValue: {
    fontSize: 12,
    color: C.textSecondary,
    fontFamily: 'monospace',
  },

  // SNS Card Type Selector
  snsTypeSelector: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  snsTypeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 6,
    backgroundColor: C.backgroundSurfaceAlt,
    gap: 8,
    minHeight: 48,
    ...SHADOW_TOKENS.none,
  },
  snsTypeText: {
    fontSize: 15,
    fontFamily: F.semiBold,
    fontWeight: '600',
    color: C.textSecondary,
  },
  snsTypeRatio: {
    fontSize: 12,
    fontFamily: F.regular,
    color: C.textMuted,
    backgroundColor: C.backgroundSurface,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 2,
  },

  // Card Options
  cardOptionsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 16,
  },
  cardOptionButton: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: C.backgroundSurfaceAlt,
    minHeight: 44,
    justifyContent: 'center',
    ...SHADOW_TOKENS.none,
  },
  cardOptionText: {
    fontSize: 13,
    fontFamily: F.semiBold,
    fontWeight: '600',
    color: C.textSubtle,
  },

  // SNS Card
  snsCard: {
    borderRadius: 8,
    overflow: 'hidden',
    marginBottom: 16,
  },
  snsCardInstagram: {
    width: SCREEN_WIDTH - 40,
    height: SCREEN_WIDTH - 40,
  },
  snsCardTwitter: {
    width: SCREEN_WIDTH - 40,
    height: (SCREEN_WIDTH - 40) * 9 / 16,
  },
  snsCardBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  snsCardOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: O.snsCardScrim,
  },
  snsCardContent: {
    flex: 1,
    padding: 16,
    justifyContent: 'space-between',
  },
  snsCardContentTwitter: {
    padding: 10,
  },
  snsCardImageWrapper: {
    flex: 1,
    borderRadius: 6,
    overflow: 'hidden',
    marginBottom: 12,
  },

  // Twitter unified card styles
  twitterUnifiedRow: {
    flexDirection: 'row',
    flex: 1,
    gap: 8,
  },
  twitterUnifiedImage: {
    flex: 2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  twitterUnifiedImageDense: {
    flex: 1.4,
  },
  twitterUnifiedPalette: {
    flex: 3,
    flexDirection: 'row',
    gap: 3,
  },
  twitterUnifiedPaletteDense: {
    flex: 3.6,
    gap: 2,
  },
  twitterUnifiedColorItem: {
    flex: 1,
    alignItems: 'stretch',
  },
  twitterUnifiedColorBar: {
    width: '100%',
    flex: 1,
    borderRadius: 3,
    marginBottom: 2,
  },
  twitterUnifiedColorHex: {
    width: '100%',
    textAlign: 'center',
    fontSize: 10,
    lineHeight: 11,
    minHeight: 11,
    fontWeight: '600',
    color: O.textOnColorMuted,
    fontFamily: 'monospace',
    textShadowColor: O.textShadowSns,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  twitterUnifiedColorHexDense: {
    fontSize: 10,
    fontFamily: F.regular,
    lineHeight: 11,
    minHeight: 11,
    letterSpacing: -0.15,
    textShadowColor: 'transparent',
    textShadowRadius: 0,
  },
  twitterUnifiedAnalysis: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 6,
  },
  twitterUnifiedHistogram: {
    flex: 3,
    backgroundColor: O.snsCardHistogramBg,
    borderRadius: 3,
    padding: 5,
  },
  twitterUnifiedHistogramBars: {
    flexDirection: 'row',
    height: 22,
    alignItems: 'flex-end',
    gap: 1,
  },
  twitterUnifiedHistogramLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  twitterUnifiedStats: {
    flex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    backgroundColor: O.snsCardHistogramBg,
    borderRadius: 3,
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  twitterUnifiedStatItem: {
    alignItems: 'center',
    paddingHorizontal: 3,
  },
  twitterUnifiedStatValue: {
    fontSize: 11,
    fontFamily: F.bold,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  twitterUnifiedStatLabel: {
    fontSize: 10,
    fontFamily: F.regular,
    color: O.textOnColorFaint,
    marginTop: 1,
  },
  snsCardImage: {
    width: '100%',
    height: '100%',
  },
  snsCardPalette: {
    flexDirection: 'row',
    gap: 8,
  },
  snsCardPaletteDense: {
    gap: 4,
  },
  snsCardColorItem: {
    flex: 1,
    alignItems: 'center',
  },
  snsCardColorSwatch: {
    width: '100%',
    height: 48,
    borderRadius: 4,
    marginBottom: 4,
  },
  snsCardColorHex: {
    width: '100%',
    textAlign: 'center',
    fontSize: 10,
    lineHeight: 11,
    minHeight: 11,
    fontWeight: '600',
    color: O.textOnColorMuted,
    fontFamily: 'monospace',
    textShadowColor: O.textShadowSns,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  snsCardColorHexDense: {
    fontSize: 10,
    fontFamily: F.regular,
    lineHeight: 11,
    minHeight: 11,
    letterSpacing: -0.1,
  },
  snsCardHistogram: {
    backgroundColor: O.snsCardHistogramBg,
    borderRadius: 5,
    padding: 10,
    marginTop: 10,
  },
  snsCardHistogramBars: {
    flexDirection: 'row',
    height: 30,
    alignItems: 'flex-end',
    gap: 1,
  },
  snsCardHistogramBarWrapper: {
    flex: 1,
    height: '100%',
    justifyContent: 'flex-end',
  },
  snsCardHistogramBar: {
    width: '100%',
    borderRadius: 1,
    minHeight: 2,
  },
  snsCardHistogramLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  snsCardHistogramLabel: {
    fontSize: 10,
    fontFamily: F.regular,
    color: O.textOnColorFaint,
  },
  snsCardStats: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: O.snsCardHistogramBg,
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginTop: 12,
  },
  snsCardStatItem: {
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  snsCardStatValue: {
    fontSize: 17,
    fontFamily: F.bold,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  snsCardStatLabel: {
    fontSize: 11,
    fontFamily: F.regular,
    color: O.textOnColorFaint,
    marginTop: 2,
  },
  snsCardStatDivider: {
    width: 1,
    height: 24,
    backgroundColor: O.snsCardStatDivider,
  },
  snsCardWatermark: {
    alignItems: 'center',
    marginTop: 8,
    transform: [{ translateY: 2 }],
  },
  snsCardWatermarkText: {
    fontSize: 12,
    color: O.textOnColorGhost,
    fontFamily: 'Pretendard-Bold',
    letterSpacing: 0.25,
  },

  // Format Selection
  formatSection: {
    marginBottom: 16,
  },
  formatSectionTitle: {
    fontSize: 13,
    color: C.textMuted,
    fontFamily: F.semiBold,
    fontWeight: '600',
    marginBottom: 10,
    letterSpacing: 0.5,
  },
  formatOptions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  formatOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 14,
    borderRadius: 5,
    backgroundColor: C.backgroundSurfaceAlt,
    gap: 6,
    minHeight: 50,
    ...SHADOW_TOKENS.none,
  },
  formatOptionText: {
    fontSize: 14,
    fontFamily: F.semiBold,
    fontWeight: '600',
    color: C.textSecondary,
  },
  exportConfirmButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.accentPrimary,
    paddingVertical: 16,
    borderRadius: 6,
    gap: 8,
    marginBottom: 16,
    ...SHADOW_TOKENS.subtle,
  },
  exportConfirmButtonText: {
    fontSize: 17,
    fontFamily: F.semiBold,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  quickCopySection: {
    marginBottom: 8,
  },
  quickCopyTitle: {
    fontSize: 13,
    color: C.textMuted,
    fontFamily: F.semiBold,
    fontWeight: '600',
    marginBottom: 10,
  },
  quickCopyButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  quickCopyButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 5,
    backgroundColor: C.backgroundSurfaceAlt,
    minHeight: 44,
    ...SHADOW_TOKENS.none,
  },
  quickCopyButtonText: {
    fontSize: 14,
    fontFamily: F.semiBold,
    fontWeight: '600',
    color: C.textSecondary,
  },

  // Histogram - Neumorphic Group
  // Histogram - Compact
  histogramCard: {
    padding: 14,
  },
  histogramHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  histogramTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  histogramTitle: {
    fontSize: 11,
    fontFamily: F.semiBold,
    fontWeight: '600',
    color: C.textMuted,
    letterSpacing: 0.5,
  },
  histogramStats: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  histogramStatText: {
    fontSize: 15,
    color: C.accentPrimary,
    fontFamily: F.bold,
    fontWeight: '700',
  },
  histogramContrastLabel: {
    fontSize: 11,
    fontFamily: F.regular,
    color: C.textMuted,
    marginRight: 6,
  },
  histogramBars: {
    flexDirection: 'row',
    height: 60,
    alignItems: 'flex-end',
    marginTop: 10,
    gap: 1,
  },
  histogramBarWrapper: {
    flex: 1,
    height: '100%',
    justifyContent: 'flex-end',
  },
  histogramBar: {
    width: '100%',
    borderRadius: 1,
    minHeight: 2,
  },
  histogramBarEmpty: {
    height: 8,
    backgroundColor: C.borderNeutral,
  },
  histogramEmptyText: {
    fontSize: 12,
    fontFamily: F.regular,
    color: C.textMuted,
  },
  histogramScale: {
    marginTop: 6,
  },
  histogramGradient: {
    flexDirection: 'row',
    height: 6,
    borderRadius: 3,
    overflow: 'hidden',
  },
  histogramGradientStep: {
    flex: 1,
  },
  histogramStatsRow: {
    flexDirection: 'row',
    marginTop: 10,
    gap: 6,
  },
  histogramStatItem: {
    flex: 1,
    backgroundColor: C.backgroundSurfaceAlt,
    borderRadius: 3,
    paddingVertical: 6,
    paddingHorizontal: 4,
    alignItems: 'center',
  },
  histogramStatItemAvg: {
    backgroundColor: C.backgroundSurfaceAlt,
  },
  histogramStatLabel: {
    fontSize: 10,
    fontFamily: F.regular,
    color: C.textSubtle,
    marginTop: 2,
  },
  histogramStatValue: {
    fontSize: 14,
    color: C.textPrimary,
    fontFamily: F.semiBold,
    fontWeight: '600',
  },
  histogramStatValueAvg: {
    fontSize: 14,
    color: C.accentPrimary,
    fontFamily: F.bold,
    fontWeight: '700',
  },

  // Camera
  cameraContainer: {
    flex: 1,
    backgroundColor: C.textPrimary,
  },
  camera: {
    ...StyleSheet.absoluteFillObject,
  },
  cameraOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'space-between',
  },
  cameraCloseButton: {
    marginTop: 10,
    marginLeft: 20,
    width: 44,
    height: 44,
    borderRadius: 11,
    backgroundColor: O.cameraCloseBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraBottomControls: {
    alignItems: 'center',
    marginBottom: 30,
  },
  captureButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: O.glassCaptureButton,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#FFFFFF',
  },
  captureButtonInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFFFFF',
  },

  // Info Modal
  infoModalContent: {
    width: SCREEN_WIDTH - 60,
    borderRadius: 10,
    padding: 24,
    alignItems: 'center',
    minHeight: 520,
    ...SHADOW_TOKENS.elevated,
  },
  infoModalHeader: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 132,
    marginBottom: 16,
  },
  infoHeaderLogoMark: {
    width: 54,
    height: 54,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  infoHeaderLogoImage: {
    width: 34,
    height: 34,
  },
  infoHeaderLogoFallbackIcon: {
    opacity: 0.95,
  },
  infoModalTitle: {
    fontSize: 26,
    fontFamily: F.bold,
    fontWeight: '700',
  },
  infoModalVersion: {
    fontSize: 14,
    fontFamily: F.regular,
    marginTop: 4,
    letterSpacing: 0.3,
  },
  infoModalVersionNum: {
    fontSize: 12,
    fontFamily: F.regular,
    marginTop: 2,
    opacity: 0.6,
  },
  infoModalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: 52,
    borderRadius: 6,
    gap: 8,
    marginBottom: 14,
    ...SHADOW_TOKENS.none,
  },
  infoModalButtonText: {
    fontSize: 16,
    fontFamily: F.semiBold,
    fontWeight: '600',
    lineHeight: 20,
  },
  infoModalLanguageSection: {
    width: '100%',
    minHeight: 88,
    marginBottom: 14,
  },
  infoModalLanguageLabel: {
    fontSize: 12,
    fontFamily: F.semiBold,
    fontWeight: '600',
    letterSpacing: 0.4,
    marginBottom: 10,
    lineHeight: 14,
  },
  infoModalLanguageToggleRow: {
    width: '100%',
    flexDirection: 'row',
    gap: 8,
  },
  infoModalLanguageButton: {
    flex: 1,
    height: 42,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    ...SHADOW_TOKENS.none,
  },
  infoModalLanguageButtonText: {
    fontSize: 14,
    fontFamily: F.bold,
    fontWeight: '700',
    lineHeight: 16,
  },
  infoModalFooter: {
    width: '100%',
    fontSize: 14,
    fontFamily: F.regular,
    textAlign: 'center',
    lineHeight: 18,
    minHeight: 36,
    marginBottom: 14,
  },
  infoModalCloseButton: {
    width: '100%',
    height: 52,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    ...SHADOW_TOKENS.subtle,
  },
  infoModalCloseButtonText: {
    fontSize: 17,
    fontFamily: F.semiBold,
    fontWeight: '600',
    lineHeight: 20,
    color: '#FFFFFF',
  },

  // Toast
  toastContainer: {
    position: 'absolute',
    top: 100,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 9999,
  },
  toastContent: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: O.blurSurfaceMedium,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    gap: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: O.glassBorderHighlight,
    ...SHADOW_TOKENS.glass,
  },
  toastText: {
    color: C.textPrimary,
    fontSize: 14,
    fontFamily: F.semiBold,
    fontWeight: '600',
  },

  // Settings Summary Bar
  summaryBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 1,
    paddingBottom: 10,
    marginTop: -6,
    overflow: 'hidden',
    backgroundColor: 'transparent',
    gap: 6,
  },
  summaryChipsScroll: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingRight: 4,
  },
  summaryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 5,
    gap: 5,
  },
  summaryChipText: {
    fontSize: 12,
    fontFamily: F.semiBold,
    fontWeight: '600',
  },
  // Inline control bar styles
  inlineSegment: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0,0,0,0.06)',
    borderRadius: 8,
    padding: 2,
  },
  inlineSegmentButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  inlineSegmentButtonActive: {
    backgroundColor: 'rgba(255,255,255,0.5)',
  },
  inlineSegmentText: {
    fontSize: 13,
    fontFamily: F.semiBold,
    fontWeight: '600',
  },
  inlineSegmentTextActive: {
    fontFamily: F.bold,
    fontWeight: '700',
  },
  inlineGearBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: 'rgba(0,0,0,0.06)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  summaryEditButton: {
    width: 32,
    height: 32,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swatchHintCard: {
    marginHorizontal: 16,
    marginTop: 2,
    marginBottom: 4,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  swatchHintIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swatchHintTextWrap: {
    flex: 1,
  },
  swatchHintTitle: {
    fontSize: 14,
    fontFamily: F.bold,
    fontWeight: '700',
    marginBottom: 2,
  },
  swatchHintSubtitle: {
    fontSize: 12,
    fontFamily: F.medium,
    fontWeight: '500',
  },

  // Inline settings panel
  inlineSettingsPanel: {
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 7,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 4,
    backgroundColor: O.blurSurfaceHeavy,
    ...SHADOW_TOKENS.subtle,
  },
  inlineSettingsHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  inlineSettingsTitle: {
    fontSize: 15,
    fontFamily: F.bold,
    fontWeight: '700',
    marginBottom: 2,
  },
  inlineSettingsSubtitle: {
    fontSize: 12,
    fontFamily: F.medium,
    fontWeight: '500',
  },
  inlineSettingsCloseBtn: {
    width: 30,
    height: 30,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Empty workspace guide
  emptyGuideCard: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 0,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.8)',
    shadowColor: '#000',
    shadowOffset: { width: 3, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  emptyGuideTitle: {
    fontSize: 14,
    fontFamily: F.bold,
    fontWeight: '700',
    marginBottom: 8,
  },
  emptyGuideRows: {
    gap: 8,
  },
  emptyGuideRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  emptyGuideText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: F.medium,
    fontWeight: '500',
  },

  // Advanced Settings Sheet
  advancedOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  advancedBackground: {
    flex: 1,
  },
  advancedContent: {
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    paddingHorizontal: 20,
    paddingBottom: 40,
    maxHeight: '80%',
  },
  advancedHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 16,
  },
  advancedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  advancedTitle: {
    fontSize: 22,
    fontFamily: F.bold,
    fontWeight: '700',
  },
  advancedScroll: {
    maxHeight: 500,
  },
  advancedSectionLabel: {
    fontSize: 12,
    fontFamily: F.semiBold,
    fontWeight: '600',
    letterSpacing: 0.5,
    textTransform: 'uppercase' as const,
    marginBottom: 8,
    marginTop: 4,
  },
  advancedPresetRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 12,
  },
  advancedPresetButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 6,
    gap: 4,
    ...SHADOW_TOKENS.none,
  },
  advancedPresetButtonCompact: {
    paddingVertical: 10,
  },
  advancedPresetInline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    maxWidth: '100%',
  },
  advancedPresetLabelWrap: {
    flexShrink: 1,
    minWidth: 0,
    alignItems: 'flex-start',
  },
  advancedPresetLabelWrapCompact: {
    alignItems: 'center',
  },
  advancedPresetText: {
    fontSize: 11,
    lineHeight: 11.5,
    fontFamily: F.bold,
    fontWeight: '700',
    textAlign: 'left',
  },
  advancedPresetTextCompact: {
    fontSize: 10.5,
    fontFamily: F.regular,
    lineHeight: 10.5,
    textAlign: 'center',
  },
  advancedMethodRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 20,
  },
  advancedMethodButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 6,
    gap: 2,
    ...SHADOW_TOKENS.none,
  },
  advancedMethodTitle: {
    fontSize: 15,
    fontFamily: F.bold,
    fontWeight: '700',
  },
  advancedMethodDesc: {
    fontSize: 12,
    fontFamily: F.regular,
  },
  advancedColorCount: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    gap: 12,
    marginBottom: 20,
  },
  advancedStepperBtn: {
    width: 36,
    height: 36,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    ...SHADOW_TOKENS.none,
  },
  advancedCountBadge: {
    width: 44,
    height: 36,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  advancedCountText: {
    fontSize: 19,
    fontFamily: F.bold,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  advancedToggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: C.borderSoft,
    marginBottom: 16,
  },
  advancedToggleLabel: {
    fontSize: 16,
    fontFamily: F.semiBold,
    fontWeight: '600',
  },
  advancedToggleDesc: {
    fontSize: 12,
    fontFamily: F.regular,
    marginTop: 2,
  },
  advancedToggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 4,
    gap: 4,
  },
  advancedToggleButtonText: {
    fontSize: 14,
    fontFamily: F.semiBold,
    fontWeight: '600',
  },
  advancedCvdGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  advancedCvdCard: {
    width: '48%',
    flexGrow: 1,
    paddingVertical: 8,
    paddingHorizontal: 9,
    borderRadius: 5,
    alignItems: 'center',
    gap: 2,
    position: 'relative',
    ...SHADOW_TOKENS.none,
  },
  cvdBarPair: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 2,
  },
  cvdBar: {
    width: 20,
    height: 8,
    borderRadius: 3,
  },
  cvdBarSlash: {
    width: 1,
    height: 8,
    transform: [{ rotate: '20deg' }],
    opacity: 0.3,
  },
  advancedCvdLabel: {
    fontSize: 13,
    fontFamily: F.semiBold,
    fontWeight: '600',
  },
  advancedCvdDesc: {
    fontSize: 10,
    fontFamily: F.regular,
    lineHeight: 12,
  },
  cvdCheck: {
    position: 'absolute',
    top: 6,
    right: 6,
  },
});
