import { StyleSheet, Dimensions } from 'react-native';
import { COLOR_TOKENS, SHADOW_TOKENS, OVERLAY_TOKENS } from '../../constants/designTokens';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const C = COLOR_TOKENS;
const O = OVERLAY_TOKENS;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.backgroundApp,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerLogoMark: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: C.accentPrimary,
    justifyContent: 'center',
    alignItems: 'center',
    ...SHADOW_TOKENS.neumorphicMedium,
  },
  headerLogoImage: {
    width: 25,
    height: 25,
  },
  headerLogoFallbackIcon: {
    opacity: 0.95,
  },
  headerSubtitle: {
    fontSize: 11,
    fontWeight: '500',
    letterSpacing: 0.3,
    marginTop: 2,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  title: {
    fontSize: 23,
    fontFamily: 'SpaceGrotesk_700Bold',
    color: C.textPrimary,
    letterSpacing: -0.45,
  },
  headerButton: {
    padding: 8,
    backgroundColor: C.backgroundElevated,
    borderRadius: 12,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  content: {
    flex: 1,
  },

  // Image Card
  imageCard: {
    marginHorizontal: 16,
    height: 240,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: C.backgroundSurface,
    borderWidth: 1,
    borderColor: C.borderSoft,
    ...SHADOW_TOKENS.neumorphicMedium,
  },
  image: {
    width: '100%',
    height: '100%',
  },
  sourceImageBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: O.scrimDark,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  sourceImageText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: O.glassWhiteLoading,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: C.textPrimary,
    marginTop: 12,
  },
  reExtractIconButton: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: O.scrimDark,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loupe: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    backgroundColor: O.glassWhiteThin,
    justifyContent: 'center',
    alignItems: 'center',
    ...SHADOW_TOKENS.glassmorphism,
  },
  loupeCrosshair: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#fff',
  },
  valueOverlayButton: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: O.glassWhiteThin,
  },
  valueOverlayButtonText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.35,
  },
  imageCardEmpty: {
    marginHorizontal: 16,
    height: 260,
    borderRadius: 20,
    backgroundColor: C.backgroundSurface,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    borderWidth: 1,
    borderColor: C.borderSoft,
    overflow: 'hidden',
    ...SHADOW_TOKENS.neumorphicMedium,
  },
  emptyIconCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  emptyIconInner: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageCardEmptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: C.textPrimary,
    marginBottom: 4,
  },
  imageCardEmptySubtitle: {
    fontSize: 13,
    fontWeight: '500',
    marginBottom: 20,
  },
  imageSourceButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  imageSourceButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 110,
    height: 80,
    borderRadius: 16,
    backgroundColor: C.backgroundSurface,
    gap: 8,
    borderWidth: 1,
    borderColor: C.borderSoft,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  imageSourceIconBg: {
    width: 38,
    height: 38,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageSourceButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: C.textPrimary,
  },

  // Style Filters - Icon Grid
  styleFiltersContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
    gap: 6,
  },
  styleFilterButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: C.backgroundElevated,
    gap: 4,
    borderWidth: 1,
    borderColor: C.borderSoft,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  styleFilterText: {
    fontSize: 11,
    color: C.textSecondary,
    fontWeight: '700',
    letterSpacing: 0.2,
  },

  // CVD Simulation Row
  cvdRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginHorizontal: 16,
    marginBottom: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 4,
  },
  cvdLabel: {
    fontSize: 10,
    fontWeight: '600' as const,
    marginRight: 6,
  },
  cvdToggleGroup: {
    flex: 1,
    flexDirection: 'row' as const,
    gap: 3,
    backgroundColor: C.backgroundSurfaceAlt,
    borderRadius: 10,
    padding: 3,
  },
  cvdOption: {
    flex: 1,
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: 'center' as const,
  },
  cvdOptionText: {
    fontSize: 11,
    fontWeight: '600' as const,
  },

  // Color Cards
  colorCardsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 8,
  },
  colorCard: {
    flex: 1,
    alignItems: 'center',
    minHeight: 48,
    paddingVertical: 2,
  },
  colorCardSelected: {
    transform: [{ scale: 1.08 }],
  },
  colorSwatch: {
    width: '100%',
    height: 52,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: C.borderSoft,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  colorSwatchSelected: {
    borderWidth: 3,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  cvdSplitOriginal: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '50%',
  },
  chipTriangle: {
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderBottomWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    marginTop: 4,
  },
  chipRank: {
    fontSize: 9,
    fontWeight: '600',
    marginTop: 2,
  },
  colorCardsEmpty: {
    opacity: 0.6,
  },
  colorSwatchEmpty: {
    backgroundColor: C.backgroundSurfaceAlt,
    borderStyle: 'dashed',
    borderWidth: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Settings Row (2-row layout)
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 14,
    gap: 10,
  },
  settingsColumn: {
    flex: 1,
    gap: 4,
  },
  algorithmToggle: {
    flexDirection: 'row' as const,
    gap: 2,
    backgroundColor: C.backgroundSurfaceAlt,
    borderRadius: 12,
    padding: 3,
  },
  algorithmOption: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  algorithmOptionText: {
    fontSize: 12,
    fontWeight: '600' as const,
  },
  algorithmDesc: {
    fontSize: 10,
    fontWeight: '500' as const,
    marginLeft: 6,
  },
  valueCheckButton: {
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    gap: 1,
  },
  valueCheckText: {
    fontSize: 12,
    fontWeight: '600' as const,
  },
  valueCheckSubtext: {
    fontSize: 9,
    fontWeight: '500' as const,
  },
  settingsColorColumn: {
    alignItems: 'center' as const,
    gap: 4,
  },
  settingsColorStepper: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
  },
  settingsDropdownLabel: {
    fontSize: 10,
    fontWeight: '500' as const,
  },
  colorStepperBtn: {
    width: 26,
    height: 26,
    borderRadius: 7,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  colorCountBadge: {
    width: 28,
    height: 26,
    borderRadius: 7,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  colorCountBadgeText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: '#FFFFFF',
  },

  // Inline Color Detail
  inlineColorDetail: {
    marginHorizontal: 16,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  inlineColorDetailHeader: {
    flexDirection: 'row',
    gap: 12,
  },
  inlineColorSwatch: {
    width: 60,
    height: 60,
    borderRadius: 10,
  },
  inlineColorValues: {
    flex: 1,
    gap: 4,
  },
  inlineColorValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 8,
    gap: 8,
    minHeight: 44,
  },
  inlineColorLabel: {
    fontSize: 10,
    fontWeight: '600',
    width: 28,
  },
  inlineColorValue: {
    flex: 1,
    fontSize: 12,
    fontFamily: 'monospace',
  },
  inlineColorPreview: {
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
  },
  previewTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inlineColorPreviewValue: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'monospace',
  },
  inlineColorCopyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: O.darkOnColorLight,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
  },
  inlineColorCopyText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },
  previewChannelContainer: {
    marginTop: 10,
    minHeight: 56,
    justifyContent: 'center',
  },
  previewChannelBars: {
    gap: 5,
  },
  previewChannelBarsPlaceholder: {
    height: 56,
  },
  previewChannelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  previewChannelLabel: {
    fontSize: 11,
    fontWeight: '700',
    width: 14,
    textAlign: 'center',
    color: O.textOnColorPrimary,
    textShadowColor: O.textShadowDark,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  previewChannelTrack: {
    flex: 1,
    height: 8,
    backgroundColor: O.darkOnColorTrack,
    borderRadius: 4,
    overflow: 'hidden',
  },
  previewChannelFill: {
    height: '100%',
    borderRadius: 4,
  },
  previewChannelValue: {
    fontSize: 10,
    fontWeight: '600',
    fontFamily: 'monospace',
    width: 32,
    textAlign: 'right',
    color: O.textOnColorPrimary,
    textShadowColor: O.textShadowDark,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  formatSegment: {
    flexDirection: 'row',
    borderRadius: 10,
    padding: 3,
    marginBottom: 12,
  },
  formatSegmentButton: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
  },
  formatSegmentText: {
    fontSize: 12,
    fontWeight: '700',
  },

  inlineVariationsSection: {
    marginTop: 0,
    borderRadius: 10,
    padding: 12,
  },

  // Slider - Inline
  sliderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  sliderLabel: {
    color: C.textSecondary,
    fontSize: 12,
    fontWeight: '500',
    marginRight: 10,
  },
  sliderInline: {
    flex: 1,
    height: 32,
  },
  countBadge: {
    backgroundColor: C.accentPrimary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginLeft: 8,
  },
  countBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },

  // Action Bar
  actionBar: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 16,
    paddingBottom: 40,
    backgroundColor: 'rgba(255,255,255,0.55)',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.60)',
    ...SHADOW_TOKENS.glassmorphism,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: C.backgroundElevated,
    gap: 6,
    borderWidth: 1,
    borderColor: C.borderSoft,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  actionButtonText: {
    color: C.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  saveButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: C.accentPrimary,
    gap: 6,
    ...SHADOW_TOKENS.neumorphicMedium,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  exportButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: C.backgroundElevated,
    gap: 6,
    borderWidth: 1,
    borderColor: C.borderSoft,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  exportButtonText: {
    color: C.accentPrimary,
    fontSize: 13,
    fontWeight: '600',
  },

  // Color Detail Modal
  colorDetailOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  colorDetailBackground: {
    flex: 1,
  },
  colorDetailContent: {
    backgroundColor: C.backgroundSurface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: 40,
    maxHeight: '70%',
    ...SHADOW_TOKENS.neumorphicMedium,
  },
  colorDetailHandle: {
    width: 40,
    height: 4,
    backgroundColor: C.borderHandle,
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 16,
  },
  colorDetailHeader: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  colorDetailSwatch: {
    width: 80,
    height: 80,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: C.borderSoft,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  colorDetailValues: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'center',
    gap: 6,
  },
  colorValueCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.backgroundSurfaceAlt,
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  colorValueCompactLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: C.textSubtle,
    width: 28,
  },
  colorValueCompactText: {
    flex: 1,
    fontSize: 12,
    color: C.textPrimary,
    fontFamily: 'monospace',
  },
  // Modal Color Preview
  modalColorPreview: {
    height: 100,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  modalColorPreviewValue: {
    flex: 1,
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'monospace',
  },
  modalColorCopyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: O.darkOnColorLight,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    gap: 6,
  },
  modalColorCopyText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  modalFormatSegment: {
    flexDirection: 'row',
    borderRadius: 10,
    padding: 3,
    marginBottom: 16,
  },
  modalFormatSegmentButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  modalFormatSegmentText: {
    fontSize: 13,
    fontWeight: '700',
  },

  // Value Variations
  variationsSection: {
    backgroundColor: C.backgroundSurfaceAlt,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  variationsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  variationsSectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: C.textPrimary,
  },
  hueShiftToggle: {
    flexDirection: 'row',
    backgroundColor: C.backgroundSurface,
    borderRadius: 8,
    padding: 2,
  },
  hueShiftOption: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  hueShiftOptionText: {
    fontSize: 11,
    fontWeight: '600',
    color: C.textSubtle,
  },
  variationStrip: {
    flexDirection: 'row',
    borderRadius: 8,
    overflow: 'hidden',
    marginBottom: 8,
  },
  variationCell: {
    flex: 1,
    alignItems: 'center',
  },
  variationCellBase: {
    borderWidth: 2,
    borderColor: C.accentPrimary,
    borderRadius: 4,
  },
  variationColor: {
    width: '100%',
    height: 40,
  },
  variationHex: {
    fontSize: 7,
    color: C.textSecondary,
    fontFamily: 'monospace',
    marginTop: 3,
  },
  variationLabel: {
    fontSize: 8,
    color: C.textMuted,
  },
  variationsHint: {
    fontSize: 10,
    color: C.textSubtle,
    textAlign: 'center',
    marginTop: 4,
  },

  // Color Harmony
  harmonySection: {
    backgroundColor: C.backgroundSurfaceAlt,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  harmonySectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: C.textPrimary,
    marginBottom: 12,
  },
  harmonyTypesScroll: {
    marginBottom: 8,
  },
  harmonyDesc: {
    fontSize: 11,
    marginBottom: 10,
    textAlign: 'center',
  },
  harmonyTypeButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: C.backgroundElevated,
    marginRight: 8,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  harmonyTypeText: {
    fontSize: 12,
    fontWeight: '600',
    color: C.textSubtle,
  },
  harmonyDescription: {
    fontSize: 11,
    color: C.textSecondary,
    marginBottom: 12,
    textAlign: 'center',
  },
  harmonyColorsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
  },
  harmonyColorItem: {
    alignItems: 'center',
  },
  harmonyColorSwatch: {
    width: 48,
    height: 48,
    borderRadius: 12,
    marginBottom: 6,
    borderWidth: 2,
    borderColor: C.borderSoft,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  harmonyColorSwatchBase: {
    borderColor: C.accentPrimary,
    borderWidth: 2,
  },
  harmonyColorHex: {
    fontSize: 9,
    color: C.textSecondary,
    fontFamily: 'monospace',
  },

  // Save Modal
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: C.backgroundElevated,
    borderRadius: 16,
    padding: 24,
    width: '85%',
    maxWidth: 340,
    ...SHADOW_TOKENS.neumorphicMedium,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: C.textPrimary,
    marginBottom: 16,
    textAlign: 'center',
  },
  modalInput: {
    backgroundColor: C.backgroundSurfaceAlt,
    borderRadius: 10,
    padding: 14,
    fontSize: 16,
    color: C.textPrimary,
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: C.backgroundSurfaceAlt,
    alignItems: 'center',
  },
  modalButtonPrimary: {
    backgroundColor: C.accentPrimary,
  },
  modalButtonText: {
    color: C.textSecondary,
    fontSize: 16,
    fontWeight: '600',
  },
  modalButtonTextPrimary: {
    color: '#FFFFFF',
  },

  // Export Modal
  exportModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  exportModalBackground: {
    flex: 1,
  },
  exportModalContent: {
    backgroundColor: C.backgroundSurface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: 40,
    ...SHADOW_TOKENS.neumorphicMedium,
  },
  exportModalHandle: {
    width: 40,
    height: 4,
    backgroundColor: C.borderHandle,
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 20,
  },
  exportModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  exportModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: C.textPrimary,
  },
  exportPreviewScroll: {
    maxHeight: 500,
  },

  // Palette Card for export
  paletteCard: {
    backgroundColor: C.backgroundElevated,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  paletteCardImage: {
    width: '100%',
    height: 160,
    borderRadius: 12,
    marginBottom: 12,
  },
  paletteCardSwatches: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 12,
  },
  paletteCardSwatch: {
    flex: 1,
    height: 40,
    borderRadius: 8,
  },
  paletteCardName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: C.textPrimary,
    marginBottom: 2,
  },
  paletteCardLabel: {
    fontSize: 11,
    color: C.textMuted,
    letterSpacing: 1,
    marginBottom: 12,
  },
  paletteCardColors: {
    gap: 8,
  },
  paletteCardColorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  paletteCardColorDot: {
    width: 28,
    height: 28,
    borderRadius: 6,
  },
  paletteCardColorInfo: {
    flex: 1,
  },
  paletteCardHex: {
    fontSize: 13,
    fontWeight: '600',
    color: C.textPrimary,
    fontFamily: 'monospace',
  },
  paletteCardRgb: {
    fontSize: 11,
    color: C.textSecondary,
    fontFamily: 'monospace',
  },
  paletteCardWatermark: {
    textAlign: 'center',
    fontSize: 10,
    color: C.textGhost,
    marginTop: 12,
  },
  paletteCardHistogram: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: C.borderSubtle,
  },
  paletteCardHistogramRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  paletteCardHistogramLabel: {
    fontSize: 11,
    color: C.textMuted,
  },
  paletteCardHistogramValue: {
    fontSize: 11,
    color: C.textSecondary,
    fontFamily: 'monospace',
  },

  // SNS Card Type Selector
  snsTypeSelector: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  snsTypeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: C.backgroundSurfaceAlt,
    gap: 8,
    minHeight: 48,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  snsTypeText: {
    fontSize: 14,
    fontWeight: '600',
    color: C.textSecondary,
  },
  snsTypeRatio: {
    fontSize: 11,
    color: C.textMuted,
    backgroundColor: C.backgroundSurface,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },

  // Card Options
  cardOptionsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 16,
  },
  cardOptionButton: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 20,
    backgroundColor: C.backgroundSurfaceAlt,
    minHeight: 44,
    justifyContent: 'center',
    ...SHADOW_TOKENS.neumorphicLight,
  },
  cardOptionText: {
    fontSize: 12,
    fontWeight: '600',
    color: C.textSubtle,
  },

  // SNS Card
  snsCard: {
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 16,
  },
  snsCardInstagram: {
    width: SCREEN_WIDTH - 40,
    height: SCREEN_WIDTH - 40,
  },
  snsCardTwitter: {
    width: SCREEN_WIDTH - 40,
    height: (SCREEN_WIDTH - 40) * 9 / 16,
  },
  snsCardBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  snsCardOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: O.snsCardScrim,
  },
  snsCardContent: {
    flex: 1,
    padding: 16,
    justifyContent: 'space-between',
  },
  snsCardContentTwitter: {
    padding: 10,
  },
  snsCardImageWrapper: {
    flex: 1,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 12,
  },

  // Twitter unified card styles
  twitterUnifiedRow: {
    flexDirection: 'row',
    flex: 1,
    gap: 8,
  },
  twitterUnifiedImage: {
    flex: 2,
    borderRadius: 8,
    overflow: 'hidden',
  },
  twitterUnifiedImageDense: {
    flex: 1.4,
  },
  twitterUnifiedPalette: {
    flex: 3,
    flexDirection: 'row',
    gap: 3,
  },
  twitterUnifiedPaletteDense: {
    flex: 3.6,
    gap: 2,
  },
  twitterUnifiedColorItem: {
    flex: 1,
    alignItems: 'stretch',
  },
  twitterUnifiedColorBar: {
    width: '100%',
    flex: 1,
    borderRadius: 5,
    marginBottom: 2,
  },
  twitterUnifiedColorHex: {
    width: '100%',
    textAlign: 'center',
    fontSize: 7,
    lineHeight: 9,
    minHeight: 9,
    fontWeight: '600',
    color: O.textOnColorMuted,
    fontFamily: 'monospace',
    textShadowColor: O.textShadowSns,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  twitterUnifiedColorHexDense: {
    fontSize: 6,
    lineHeight: 8,
    minHeight: 8,
    letterSpacing: -0.15,
    textShadowColor: 'transparent',
    textShadowRadius: 0,
  },
  twitterUnifiedAnalysis: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 6,
  },
  twitterUnifiedHistogram: {
    flex: 3,
    backgroundColor: O.snsCardHistogramBg,
    borderRadius: 6,
    padding: 5,
  },
  twitterUnifiedHistogramBars: {
    flexDirection: 'row',
    height: 22,
    alignItems: 'flex-end',
    gap: 1,
  },
  twitterUnifiedHistogramLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  twitterUnifiedStats: {
    flex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    backgroundColor: O.snsCardHistogramBg,
    borderRadius: 6,
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  twitterUnifiedStatItem: {
    alignItems: 'center',
    paddingHorizontal: 3,
  },
  twitterUnifiedStatValue: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  twitterUnifiedStatLabel: {
    fontSize: 6,
    color: O.textOnColorFaint,
    marginTop: 1,
  },
  snsCardImage: {
    width: '100%',
    height: '100%',
  },
  snsCardPalette: {
    flexDirection: 'row',
    gap: 8,
  },
  snsCardPaletteDense: {
    gap: 4,
  },
  snsCardColorItem: {
    flex: 1,
    alignItems: 'center',
  },
  snsCardColorSwatch: {
    width: '100%',
    height: 48,
    borderRadius: 8,
    marginBottom: 4,
  },
  snsCardColorHex: {
    width: '100%',
    textAlign: 'center',
    fontSize: 9,
    lineHeight: 11,
    minHeight: 11,
    fontWeight: '600',
    color: O.textOnColorMuted,
    fontFamily: 'monospace',
    textShadowColor: O.textShadowSns,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  snsCardColorHexDense: {
    fontSize: 8,
    lineHeight: 10,
    minHeight: 10,
    letterSpacing: -0.1,
  },
  snsCardHistogram: {
    backgroundColor: O.snsCardHistogramBg,
    borderRadius: 10,
    padding: 10,
    marginTop: 10,
  },
  snsCardHistogramBars: {
    flexDirection: 'row',
    height: 30,
    alignItems: 'flex-end',
    gap: 1,
  },
  snsCardHistogramBarWrapper: {
    flex: 1,
    height: '100%',
    justifyContent: 'flex-end',
  },
  snsCardHistogramBar: {
    width: '100%',
    borderRadius: 1,
    minHeight: 2,
  },
  snsCardHistogramLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  snsCardHistogramLabel: {
    fontSize: 8,
    color: O.textOnColorFaint,
  },
  snsCardStats: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: O.snsCardHistogramBg,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginTop: 12,
  },
  snsCardStatItem: {
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  snsCardStatValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  snsCardStatLabel: {
    fontSize: 10,
    color: O.textOnColorFaint,
    marginTop: 2,
  },
  snsCardStatDivider: {
    width: 1,
    height: 24,
    backgroundColor: O.snsCardStatDivider,
  },
  snsCardWatermark: {
    alignItems: 'center',
    marginTop: 8,
    transform: [{ translateY: 2 }],
  },
  snsCardWatermarkText: {
    fontSize: 11,
    color: O.textOnColorGhost,
    fontFamily: 'SpaceGrotesk_700Bold',
    letterSpacing: 0.25,
  },

  // Format Selection
  formatSection: {
    marginBottom: 16,
  },
  formatSectionTitle: {
    fontSize: 12,
    color: C.textMuted,
    fontWeight: '600',
    marginBottom: 10,
    letterSpacing: 0.5,
  },
  formatOptions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  formatOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: C.backgroundSurfaceAlt,
    gap: 6,
    minHeight: 50,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  formatOptionText: {
    fontSize: 13,
    fontWeight: '600',
    color: C.textSecondary,
  },
  exportConfirmButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.accentPrimary,
    paddingVertical: 16,
    borderRadius: 12,
    gap: 8,
    marginBottom: 16,
    ...SHADOW_TOKENS.neumorphicMedium,
  },
  exportConfirmButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  quickCopySection: {
    marginBottom: 8,
  },
  quickCopyTitle: {
    fontSize: 12,
    color: C.textMuted,
    fontWeight: '600',
    marginBottom: 10,
  },
  quickCopyButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  quickCopyButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: C.backgroundSurfaceAlt,
    minHeight: 44,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  quickCopyButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: C.textSecondary,
  },

  // Histogram - Compact
  histogramCard: {
    marginHorizontal: 16,
    marginTop: 4,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: C.borderSoft,
  },
  histogramHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  histogramTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  histogramTitle: {
    fontSize: 10,
    fontWeight: '600',
    color: C.textMuted,
    letterSpacing: 0.5,
  },
  histogramStats: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  histogramStatText: {
    fontSize: 14,
    color: C.accentPrimary,
    fontWeight: '700',
  },
  histogramContrastLabel: {
    fontSize: 10,
    color: C.textMuted,
    marginRight: 6,
  },
  histogramBars: {
    flexDirection: 'row',
    height: 60,
    alignItems: 'flex-end',
    marginTop: 10,
    gap: 1,
  },
  histogramBarWrapper: {
    flex: 1,
    height: '100%',
    justifyContent: 'flex-end',
  },
  histogramBar: {
    width: '100%',
    borderRadius: 1,
    minHeight: 2,
  },
  histogramBarEmpty: {
    height: 8,
    backgroundColor: C.borderNeutral,
  },
  histogramEmptyText: {
    fontSize: 11,
    color: C.textMuted,
  },
  histogramScale: {
    marginTop: 6,
  },
  histogramGradient: {
    flexDirection: 'row',
    height: 6,
    borderRadius: 3,
    overflow: 'hidden',
  },
  histogramGradientStep: {
    flex: 1,
  },
  histogramStatsRow: {
    flexDirection: 'row',
    marginTop: 10,
    gap: 6,
  },
  histogramStatItem: {
    flex: 1,
    backgroundColor: C.backgroundSurfaceAlt,
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 4,
    alignItems: 'center',
  },
  histogramStatItemAvg: {
    backgroundColor: C.backgroundSurfaceAlt,
  },
  histogramStatLabel: {
    fontSize: 9,
    color: C.textSubtle,
    marginTop: 2,
  },
  histogramStatValue: {
    fontSize: 13,
    color: C.textPrimary,
    fontWeight: '600',
  },
  histogramStatValueAvg: {
    fontSize: 13,
    color: C.accentPrimary,
    fontWeight: '700',
  },

  // Camera
  cameraContainer: {
    flex: 1,
    backgroundColor: C.textPrimary,
  },
  camera: {
    ...StyleSheet.absoluteFillObject,
  },
  cameraOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'space-between',
  },
  cameraCloseButton: {
    marginTop: 10,
    marginLeft: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: O.cameraCloseBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraBottomControls: {
    alignItems: 'center',
    marginBottom: 30,
  },
  captureButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: O.glassCaptureButton,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#FFFFFF',
  },
  captureButtonInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFFFFF',
  },

  // Info Modal
  infoModalContent: {
    width: SCREEN_WIDTH - 60,
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
    minHeight: 520,
    ...SHADOW_TOKENS.neumorphicMedium,
  },
  infoModalHeader: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 132,
    marginBottom: 16,
  },
  infoHeaderLogoMark: {
    width: 54,
    height: 54,
    borderRadius: 16,
    backgroundColor: C.accentPrimary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    ...SHADOW_TOKENS.neumorphicMedium,
  },
  infoHeaderLogoImage: {
    width: 34,
    height: 34,
  },
  infoHeaderLogoFallbackIcon: {
    opacity: 0.95,
  },
  infoModalTitle: {
    fontSize: 24,
    fontWeight: '700',
  },
  infoModalVersion: {
    fontSize: 13,
    marginTop: 4,
    letterSpacing: 0.3,
  },
  infoModalVersionNum: {
    fontSize: 11,
    marginTop: 2,
    opacity: 0.6,
  },
  infoModalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: 52,
    borderRadius: 12,
    gap: 8,
    marginBottom: 14,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  infoModalButtonText: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 20,
  },
  infoModalLanguageSection: {
    width: '100%',
    minHeight: 88,
    marginBottom: 14,
  },
  infoModalLanguageLabel: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.4,
    marginBottom: 10,
    lineHeight: 14,
  },
  infoModalLanguageToggleRow: {
    width: '100%',
    flexDirection: 'row',
    gap: 8,
  },
  infoModalLanguageButton: {
    flex: 1,
    height: 42,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    ...SHADOW_TOKENS.neumorphicLight,
  },
  infoModalLanguageButtonText: {
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 16,
  },
  infoModalFooter: {
    width: '100%',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
    minHeight: 36,
    marginBottom: 14,
  },
  infoModalCloseButton: {
    width: '100%',
    height: 52,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    ...SHADOW_TOKENS.neumorphicMedium,
  },
  infoModalCloseButtonText: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 20,
    color: '#FFFFFF',
  },

  // Toast
  toastContainer: {
    position: 'absolute',
    top: 100,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 9999,
  },
  toastContent: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.backgroundSurface,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: `${C.success}40`,
    ...SHADOW_TOKENS.neumorphicMedium,
  },
  toastText: {
    color: C.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },

  // Settings Summary Bar
  summaryBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    paddingLeft: 12,
    paddingRight: 8,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: O.glassWhite,
    gap: 6,
    borderWidth: 1,
    borderColor: O.glassWhiteBorder,
    ...SHADOW_TOKENS.glassmorphism,
  },
  summaryChipsScroll: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingRight: 4,
  },
  summaryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 9,
    gap: 5,
  },
  summaryChipText: {
    fontSize: 10.5,
    fontWeight: '600',
  },
  summaryEditButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swatchHintCard: {
    marginHorizontal: 16,
    marginTop: 2,
    marginBottom: 4,
    borderRadius: 12,
    borderWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  swatchHintIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swatchHintTextWrap: {
    flex: 1,
  },
  swatchHintTitle: {
    fontSize: 12.5,
    fontWeight: '700',
    marginBottom: 2,
  },
  swatchHintSubtitle: {
    fontSize: 11,
    fontWeight: '500',
  },

  // Inline settings panel
  inlineSettingsPanel: {
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 4,
    backgroundColor: 'rgba(255,255,255,0.50)',
    ...SHADOW_TOKENS.neumorphicLight,
  },
  inlineSettingsHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  inlineSettingsTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 2,
  },
  inlineSettingsSubtitle: {
    fontSize: 11,
    fontWeight: '500',
  },
  inlineSettingsCloseBtn: {
    width: 30,
    height: 30,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Empty workspace guide
  emptyGuideCard: {
    marginHorizontal: 16,
    marginTop: 2,
    marginBottom: 14,
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  emptyGuideTitle: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 8,
  },
  emptyGuideRows: {
    gap: 8,
  },
  emptyGuideRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  emptyGuideText: {
    flex: 1,
    fontSize: 11.5,
    lineHeight: 16,
    fontWeight: '500',
  },

  // Advanced Settings Sheet
  advancedOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  advancedBackground: {
    flex: 1,
  },
  advancedContent: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: 40,
    maxHeight: '80%',
  },
  advancedHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 16,
  },
  advancedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  advancedTitle: {
    fontSize: 20,
    fontWeight: '700',
  },
  advancedScroll: {
    maxHeight: 500,
  },
  advancedSectionLabel: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
    textTransform: 'uppercase' as const,
    marginBottom: 8,
    marginTop: 4,
  },
  advancedPresetRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
  },
  advancedPresetButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    gap: 4,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  advancedPresetButtonCompact: {
    paddingVertical: 8,
  },
  advancedPresetInline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    maxWidth: '100%',
  },
  advancedPresetLabelWrap: {
    flexShrink: 1,
    minWidth: 0,
    alignItems: 'flex-start',
  },
  advancedPresetLabelWrapCompact: {
    alignItems: 'center',
  },
  advancedPresetText: {
    fontSize: 10,
    lineHeight: 11.5,
    fontWeight: '700',
    textAlign: 'left',
  },
  advancedPresetTextCompact: {
    fontSize: 9.5,
    lineHeight: 10.5,
    textAlign: 'center',
  },
  advancedMethodRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 20,
  },
  advancedMethodButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 12,
    gap: 2,
    ...SHADOW_TOKENS.neumorphicLight,
  },
  advancedMethodTitle: {
    fontSize: 14,
    fontWeight: '700',
  },
  advancedMethodDesc: {
    fontSize: 11,
  },
  advancedColorCount: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    gap: 12,
    marginBottom: 20,
  },
  advancedStepperBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    ...SHADOW_TOKENS.neumorphicLight,
  },
  advancedCountBadge: {
    width: 44,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  advancedCountText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  advancedToggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: C.borderSoft,
    marginBottom: 16,
  },
  advancedToggleLabel: {
    fontSize: 15,
    fontWeight: '600',
  },
  advancedToggleDesc: {
    fontSize: 11,
    marginTop: 2,
  },
  advancedToggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 4,
  },
  advancedToggleButtonText: {
    fontSize: 13,
    fontWeight: '600',
  },
  advancedCvdGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  advancedCvdCard: {
    width: '48%',
    flexGrow: 1,
    paddingVertical: 8,
    paddingHorizontal: 9,
    borderRadius: 10,
    alignItems: 'center',
    gap: 2,
    position: 'relative',
    ...SHADOW_TOKENS.neumorphicLight,
  },
  cvdBarPair: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 2,
  },
  cvdBar: {
    width: 20,
    height: 8,
    borderRadius: 3,
  },
  cvdBarSlash: {
    width: 1,
    height: 8,
    transform: [{ rotate: '20deg' }],
    opacity: 0.3,
  },
  advancedCvdLabel: {
    fontSize: 12,
    fontWeight: '600',
  },
  advancedCvdDesc: {
    fontSize: 9,
    lineHeight: 12,
  },
  cvdCheck: {
    position: 'absolute',
    top: 6,
    right: 6,
  },
});
